##  try- except 구문 활용

- 특이한 경우 에러케이스를 except 을 통하여 함수 error를 차단할 수 있다.

  - 과제 4 baseball game에서 활용

    ````python
    def is_digit(user_input_number):
        try:
            int(user_input_number)
            return True
        except ValueError: # "12.2"은 type이 "str"이고 int("12.2")는 ValueError가 뜬다
            return False
    ````

    - is_digit(user_input_number) 함수에서 user_input_number가 세자리 자연수일 때만 True를 return 해야하므로 ValueError나오는 경우를 이와 같이 차단시킬 수 있다.

  - 과제 5 morse code에서 활용

    ```python
    def decoding_character(morse_character):
      morse_code_dict = get_morse_code_dict()
      morse_code_dict_reverse = {j : i for i, j in morse_code_dict.items() }
      try:
        return morse_code_dict_reverse[morse_character]
      except KeyError: #morse_character이 ''이면 ''으로 변환되어야하지만 ''은 애초에 morse_code_dict안에 존재하지 않아 morse_code_dict_reverse의 Key값에 주어져 있지 않다. 하지만 변환이 가능하므로 위와 같은 (유일하게) KeyError가 났을때 ''으로 바꿀 수 있도록 해야한다.
        return ''
    ```

  - -try~except~finally까지 활용이 가능하다

    ```python
    try:
        for i in range(100):
            for j in range(100):
                result = i//j
                print(result)
    except ZeroDivisionError:
        print("나눌 수 없습니다.")
    finally:
        print("끝났습니다!")
    ```

    - finally는 예외 발생 여부와 상관없이 실행되는 구문이다.

